import Macaulean.Interpreter.Run

/-! Explicit expected values shared by kernel and independent native-M2 tests. -/
namespace Macaulean.M2.CollectionCases

-- Values are written as data, not obtained by parsing the expected M2 output.
def successes : List (String × Value) := [
  ("{}", .list []),
  ("()", .sequence []),
  ("(7)", .zz 7),
  ("{7}", .list [.zz 7]),
  ("1:7", .sequence [.zz 7]),
  ("(1,)", .sequence [.zz 1, .null]),
  ("(,1)", .sequence [.null, .zz 1]),
  ("(,)", .sequence [.null, .null]),
  ("{,}", .list [.null, .null]),
  ("{1,}", .list [.zz 1, .null]),
  ("{,1}", .list [.null, .zz 1]),
  ("(1,,3)", .sequence [.zz 1, .null, .zz 3]),
  ("{1,,3}", .list [.zz 1, .null, .zz 3]),
  ("1,2,3", .sequence [.zz 1, .zz 2, .zz 3]),
  ("((1,2),3)", .sequence [.sequence [.zz 1, .zz 2], .zz 3]),
  ("(1,(2,3))", .sequence [.zz 1, .sequence [.zz 2, .zz 3]]),
  ("{(1,2)}", .list [.sequence [.zz 1, .zz 2]]),
  ("{1..3}", .list [.sequence [.zz 1, .zz 2, .zz 3]]),
  ("{(), {}, {1, (2,3)}}", .list [.sequence [], .list [], .list [.zz 1, .sequence [.zz 2, .zz 3]]]),
  ("{1/1, 2/3, true, null}", .list [.qq (mkRat 1 1), .qq (mkRat 2 3), .bool true, .null]),
  ("{1;2}", .list [.zz 2]),
  ("{1;}", .list [.null]),
  ("{(1;2),3}", .list [.zz 2, .zz 3]),
  ("(1;2,3)", .sequence [.zz 2, .zz 3]),
  ("(1,2;3)", .zz 3),
  ("{1,2;}", .list [.null]),
  ("({1,2};)", .null),
  ("{if true then 1 else 2,3}", .list [.zz 1, .zz 3]),
  ("if true then 1 else 2,3", .sequence [.zz 1, .zz 3]),
  ("if false then {1/0} else (1,2)", .sequence [.zz 1, .zz 2]),
  ("if false then {1}", .null),
  ("false and {}#0", .bool false),
  ("true or {}#0", .bool true),
  ("1..3", .sequence [.zz 1, .zz 2, .zz 3]),
  ("1..<3", .sequence [.zz 1, .zz 2]),
  ("1..1", .sequence [.zz 1]),
  ("1..<1", .sequence []),
  ("2..1", .sequence []),
  ("2..<1", .sequence []),
  ("(-2)..1", .sequence [.zz (-2), .zz (-1), .zz 0, .zz 1]),
  ("(-2)..<1", .sequence [.zz (-2), .zz (-1), .zz 0]),
  ("1+1..2+2", .sequence [.zz 2, .zz 3, .zz 4]),
  ("2:7", .sequence [.zz 7, .zz 7]),
  ("0:7", .sequence []),
  ("(-1):7", .sequence []),
  ("2:(1,2)", .sequence [.sequence [.zz 1, .zz 2], .sequence [.zz 1, .zz 2]]),
  ("1:()", .sequence [.sequence []]),
  ("1:null", .sequence [.null]),
  ("#{}", .zz 0),
  ("#()", .zz 0),
  ("#{1,2,3}", .zz 3),
  ("#(1,)", .zz 2),
  ("#{1..3}", .zz 1),
  ("#(1..3)", .zz 3),
  ("#{{1,2},{3}}#0", .zz 2),
  ("{10,20,30}#0", .zz 10),
  ("{10,20,30}#-1", .zz 30),
  ("{10,20,30}#-3", .zz 10),
  ("(10,20,30)#-1", .zz 30),
  ("{{1,2},{3,4}}#1#0", .zz 3),
  ("{1,}#1", .null),
  ("{10,20,30}#?(-1)", .bool true),
  ("{10,20,30}#?(-3)", .bool true),
  ("{10,20,30}#?(-4)", .bool false),
  ("{10,20,30}#?3", .bool false),
  ("(10,20,30)#?(-1)", .bool true),
  ("{}#?0", .bool false),
  ("()#?(-1)", .bool false),
  ("{1}#?true", .bool false),
  ("{1}#?(1/1)", .bool false),
  ("()#?{}", .bool false),
  ("{}#?(0,)", .bool false),
  ("(1:7)#?null", .bool false),
  ("null#?0", .bool false),
  ("null#?{}", .bool false),
  ("{1,2}|{3}", .list [.zz 1, .zz 2, .zz 3]),
  ("(1,2)|(3,4)", .sequence [.zz 1, .zz 2, .zz 3, .zz 4]),
  ("{}|{1}", .list [.zz 1]),
  ("()|(1:7)", .sequence [.zz 7]),
  ("{{1}}|{{2}}", .list [.list [.zz 1], .list [.zz 2]]),
  ("{1}=={1/1}", .bool true),
  ("(1,2)==(1/1,2)", .bool true),
  ("{null}=={null}", .bool true),
  ("{}=={}", .bool true),
  ("()==()", .bool true),
  ("{1}!={1/1}", .bool false),
  ("{1,2}=={1}", .bool false),
  ("{1,2}!={1}", .bool true),
  ("{{1,(2,3)}}=={{1/1,(2,3/1)}}", .bool true),
  ("{0,true}=={1,7}", .bool false),
  ("{true}=={}", .bool false),
  ("cp=0; {(cp=cp+1), (cp=cp+1), cp}", .list [.zz 1, .zz 2, .zz 2]),
  ("cp=0; ((cp=cp+1),(cp=cp+1),cp)", .sequence [.zz 1, .zz 2, .zz 2]),
  ("cp=0; 3:(cp=cp+1)", .sequence [.zz 1, .zz 1, .zz 1]),
  ("cp=0; 0:(cp=cp+1); cp", .zz 1),
  ("cp=0; (-1):(cp=cp+1); cp", .zz 1),
  ("cp={1,2}; cq=cp; cp=cp|{3}; cq", .list [.zz 1, .zz 2]),
  ("cp={1,2}; cq=cp; cp=cp|{3}; cp", .list [.zz 1, .zz 2, .zz 3]),
  ("cp=1,cp+1", .sequence [.zz 1, .zz 2]),
  ("cp=1,2; cp", .zz 1),
  ("{1,\n2,\n3}", .list [.zz 1, .zz 2, .zz 3]),
  ("(1,\n2,\n3)", .sequence [.zz 1, .zz 2, .zz 3]),
  ("1,\n2", .zz 2),
  ("1,\n", .sequence [.zz 1, .null]),
  ("{1, -- λ, 中文\n 2}", .list [.zz 1, .zz 2]),
  ("{0x10,0b11,0o7}", .list [.zz 16, .zz 3, .zz 7])
]

def errors : List (String × Error) := [
  ("{}#0", .indexOutOfBounds 0 0),
  ("()#0", .indexOutOfBounds 0 0),
  ("{1,2}#2", .indexOutOfBounds 2 2),
  ("{1,2}#(-3)", .indexOutOfBounds (-3) 2),
  ("{1}#(1/1)", .noMethod "#" ["List", "QQ"]),
  ("#7", .noMethod "#" ["ZZ"]),
  ("#null", .noMethod "#" ["Nothing"]),
  ("7#0", .noMethod "#" ["ZZ", "ZZ"]),
  ("1/2..3", .noMethod ".." ["QQ", "ZZ"]),
  ("1..<(3/1)", .noMethod "..<" ["ZZ", "QQ"]),
  ("true:7", .noMethod ":" ["Boolean", "ZZ"]),
  ("{1}|(2,3)", .noMethod "|" ["List", "Sequence"]),
  ("{1}==(1:1)", .noMethod "==" ["List", "Sequence"]),
  ("{true}=={1}", .noMethod "==" ["Boolean", "ZZ"]),
  ("{1}==1", .noMethod "==" ["List", "ZZ"]),
  ("if {} then 1", .conditionNotBoolean "List"),
  ("if () then 1", .conditionNotBoolean "Sequence"),
  ("{1/0,7}", .divByZero),
  ("(7,1/0)", .divByZero),
  ("0:(1/0)", .divByZero),
  ("true and {}#0", .indexOutOfBounds 0 0),
  ("{1}#0=2", .immutableCollection "List"),
  ("(1:1)#0=2", .immutableCollection "Sequence"),
  ("{1}#0=1/0", .divByZero)
]

def invalidSyntax : List String := [
  "{", "{1", "(1,2", "{1,2)", "(1,2}", "{(1,2}",
  "{1 2}", "(1 2)", "{1\n2}", "{1,,2", "{1;;}", "{;1}",
  "1...3", "1..", "1..<", "#", "{1}#", "{1}#?", "{1}.0",
  "{1}=2", "1: =2", "{1.25}", "(,1 +)", "{if true then 1 else }"
]

end Macaulean.M2.CollectionCases
