import Macaulean

open Macaulean
open Macaulean.CAS
open MRDI.CAS

namespace MacauleanTest.PermGroup

def requireIO (cond : Bool) (msg : String) : IO Unit :=
  unless cond do throw <| IO.userError msg

-- ============================================================================
-- Backend-level test: verify Oscar/GAP finds word decompositions
-- ============================================================================

-- (1 2 3) in S₃ generated by (1 2) and (2 3)
#eval do
  let descs ← getRegisteredBackends
  let oscarDescs := descs.filter fun (b : CASBackendDesc) => b.name == `Oscar
  let backends ← oscarDescs.mapM fun d => LiveBackend.new d
  let cache ← IO.mkRef ({} : CASCache)
  let ctx : CASContext := { backends, cache }
  try
    let problem : PermGroupMembershipProblem := {
      size := 3
      generators := #[#[2, 1, 3], #[1, 3, 2]]  -- (1 2) and (2 3) in 1-indexed
      target := #[2, 3, 1]                        -- (1 2 3) in 1-indexed
    }
    let response ← ctx.call (toMrdi problem)
    let result ← match fromMrdi? (α := PermGroupMembershipResult) response with
      | .ok (r : PermGroupMembershipResult) => pure r
      | .error e => throw <| IO.userError s!"decode failed: {e}"
    requireIO result.inGroup "CAS should report (1 2 3) is in <(1 2), (2 3)>"
    requireIO (result.word.size > 0) "CAS should return a non-empty word"
  finally
    ctx.cleanup

-- Harder: (1 2 3 4) in S₄ generated by (1 2) and (1 2 3 4)
#eval do
  let descs ← getRegisteredBackends
  let oscarDescs := descs.filter fun (b : CASBackendDesc) => b.name == `Oscar
  let backends ← oscarDescs.mapM fun d => LiveBackend.new d
  let cache ← IO.mkRef ({} : CASCache)
  let ctx : CASContext := { backends, cache }
  try
    let problem : PermGroupMembershipProblem := {
      size := 4
      generators := #[#[2, 1, 3, 4], #[2, 3, 4, 1]]  -- (1 2) and (1 2 3 4)
      target := #[3, 4, 1, 2]                            -- (1 3)(2 4)
    }
    let response ← ctx.call (toMrdi problem)
    let result ← match fromMrdi? (α := PermGroupMembershipResult) response with
      | .ok (r : PermGroupMembershipResult) => pure r
      | .error e => throw <| IO.userError s!"decode failed: {e}"
    requireIO result.inGroup "(1 3)(2 4) should be in S₄ = <(1 2), (1 2 3 4)>"
    requireIO (result.word.size > 0) "CAS should return a non-empty word"
  finally
    ctx.cleanup

-- ============================================================================
-- Kernel-verified tests using native_decide
-- ============================================================================

-- Verify the Perm machinery works with native_decide
-- applyWord on known word should equal target
def g1_3 : Perm 3 := ⟨#[1, 0, 2], by decide⟩  -- (0 1) = swap first two
def g2_3 : Perm 3 := ⟨#[0, 2, 1], by decide⟩  -- (1 2) = swap last two
def target_3 : Perm 3 := ⟨#[1, 2, 0], by decide⟩  -- (0 1 2) = 3-cycle

-- Manual witness: (0 1 2) = (1 2) ∘ (0 1) = g2 * g1
-- In word format: [2, 1] means apply g1 then g2
example : InPermGroup target_3 #[g1_3, g2_3] :=
  ⟨#[2, 1], by native_decide⟩

end MacauleanTest.PermGroup
