import Macaulean

open Macaulean
open Macaulean.CAS
open MRDI.CAS

namespace MacauleanTest.PermGroup

def requireIO (cond : Bool) (msg : String) : IO Unit :=
  unless cond do throw <| IO.userError msg

-- ============================================================================
-- Kernel-verified permutation group membership via cas + GAP
-- Each test: GAP finds the word, strategy resolves to concrete permutations,
-- decide verifies the composition in the kernel. Zero axioms.
-- ============================================================================

-- S₃: (0 1 2) ∈ ⟨(0 1), (1 2)⟩
def swap01_3 : Perm 3 := ⟨#[1, 0, 2], by decide⟩
def swap12_3 : Perm 3 := ⟨#[0, 2, 1], by decide⟩
def cycle012 : Perm 3 := ⟨#[1, 2, 0], by decide⟩

example : InPermGroup cycle012 #[swap01_3, swap12_3] := by cas

-- A₅ (order 60): (0 2 4 1 3) ∈ ⟨(0 1 2 3 4), (0 1 2)⟩
-- A₅ is the smallest non-abelian simple group.
-- The 5-cycle and 3-cycle generate all of A₅.
def rot5 : Perm 5 := ⟨#[1, 2, 3, 4, 0], by decide⟩      -- (0 1 2 3 4)
def cyc3 : Perm 5 := ⟨#[1, 2, 0, 3, 4], by decide⟩      -- (0 1 2)
def target_a5 : Perm 5 := ⟨#[2, 4, 0, 3, 1], by decide⟩  -- (0 2 4 1 3)

example : InPermGroup target_a5 #[rot5, cyc3] := by cas

-- S₅ (order 120): (0 2)(1 3) ∈ ⟨(0 1 2 3 4), (0 1)⟩
-- Any transposition + n-cycle generates Sₙ.
def swap01_5 : Perm 5 := ⟨#[1, 0, 2, 3, 4], by decide⟩
def dbl_trans : Perm 5 := ⟨#[2, 3, 0, 1, 4], by decide⟩  -- (0 2)(1 3)

example : InPermGroup dbl_trans #[rot5, swap01_5] := by cas

-- D₄ (dihedral group of the square, order 8):
-- (0 2) ∈ ⟨(0 1 2 3), (1 3)⟩
-- D₄ is generated by a rotation and a reflection.
-- (0 2) is the other diagonal reflection — non-trivially in D₄.
def rot4 : Perm 4 := ⟨#[1, 2, 3, 0], by decide⟩         -- rotation (0 1 2 3)
def refl13 : Perm 4 := ⟨#[0, 3, 2, 1], by decide⟩       -- reflection (1 3)
def refl02 : Perm 4 := ⟨#[2, 1, 0, 3], by decide⟩       -- reflection (0 2)

example : InPermGroup refl02 #[rot4, refl13] := by cas

-- ============================================================================
-- Backend-level tests
-- ============================================================================

-- S₅: verify (1 3)(2 4) via Oscar directly
#eval do
  let descs ← getRegisteredBackends
  let oscarDescs := descs.filter fun (b : CASBackendDesc) => b.name == `Oscar
  let backends ← oscarDescs.mapM fun d => LiveBackend.new d
  let cache ← IO.mkRef ({} : CASCache)
  let ctx : CASContext := { backends, cache }
  try
    let problem : PermGroupMembershipProblem := {
      size := 5
      generators := #[#[2, 3, 4, 5, 1], #[2, 1, 3, 4, 5]]  -- (12345) and (12)
      target := #[3, 4, 1, 2, 5]                              -- (1 3)(2 4)
    }
    let response ← ctx.call (toMrdi problem)
    let result ← match fromMrdi? (α := PermGroupMembershipResult) response with
      | .ok (r : PermGroupMembershipResult) => pure r
      | .error e => throw <| IO.userError s!"decode failed: {e}"
    requireIO result.inGroup "(1 3)(2 4) should be in S₅"
  finally
    ctx.cleanup

end MacauleanTest.PermGroup
