import Lean
import Macaulean.CAS.Strategy
import Macaulean.CAS.Tactic
import MRDI.CAS

open Lean Elab Tactic Meta
open MRDI.CAS

namespace Macaulean

/-! # Permutation Group Membership

Prove that a permutation is in the group generated by given generators.
The CAS (GAP via Oscar) finds a word decomposition, and the kernel verifies
by computing the composition — decidable on Fin n.
-/

-- ============================================================================
-- Permutation definitions (no mathlib)
-- ============================================================================

/-- A permutation on n elements, represented as an array of images.
`perm[i]` is the image of `i` under the permutation. -/
abbrev Perm (n : Nat) := Vector (Fin n) n

/-- The identity permutation. -/
def Perm.id (n : Nat) : Perm n :=
  Vector.ofFn fun i => i

/-- Compose two permutations: (σ ∘ τ)(i) = σ(τ(i)). -/
def Perm.comp {n : Nat} (σ τ : Perm n) : Perm n :=
  Vector.ofFn fun i => σ[τ[i]]

/-- Inverse of a permutation. -/
def Perm.inv {n : Nat} (σ : Perm n) : Perm n :=
  Vector.ofFn fun i =>
    -- Find j such that σ[j] = i
    let rec find (j : Nat) (h : j ≤ n) : Fin n :=
      if hj : j < n then
        if σ[j] == i then ⟨j, hj⟩
        else find (j + 1) (by omega)
      else i  -- shouldn't happen for valid permutations
    find 0 (by omega)

/-- Apply a word (list of signed generator indices) to produce a permutation.
Positive index k means generator k-1, negative means inverse of generator |k|-1. -/
def applyWord {n : Nat} (generators : Array (Perm n)) (word : Array Int) : Perm n :=
  word.foldl (init := Perm.id n) fun acc letter =>
    let idx := letter.natAbs - 1
    if h : idx < generators.size then
      let gen := generators[idx]
      let step := if letter > 0 then gen else gen.inv
      Perm.comp step acc
    else acc

/-- `InPermGroup target generators` means `target` can be expressed as a
product of the generators and their inverses. -/
def InPermGroup {n : Nat} (target : Perm n) (generators : Array (Perm n)) : Prop :=
  ∃ word : Array Int, applyWord generators word = target

-- ============================================================================
-- Strategy
-- ============================================================================

private def permToNatArray {n : Nat} (σ : Perm n) : Array Nat :=
  σ.toArray.map (·.val + 1)  -- GAP uses 1-indexed

private def executePermGroupMembership (ctx : CAS.CASContext) (goal : MVarId) :
    TacticM (List MVarId) := do
  let target ← goal.getType
  let (targetFn, targetArgs) := target.getAppFnArgs
  unless targetFn == ``Macaulean.InPermGroup && targetArgs.size == 3 do
    throwTacticEx `cas goal "Expected a goal of the form `InPermGroup target generators`"
  let nExpr := targetArgs[0]!
  let targetPermExpr := targetArgs[1]!
  let gensExpr := targetArgs[2]!
  -- Extract n
  let some n ← getNatValue? (← whnf nExpr)
    | throwTacticEx `cas goal "Expected a concrete natural number for permutation degree"
  -- Extract target permutation as array of nats (1-indexed for GAP)
  let targetPerm ← whnf targetPermExpr
  let mut targetArr : Array Nat := #[]
  for i in [:n] do
    let idx := mkNatLit i
    let val ← whnf (← mkAppM ``Vector.get #[targetPermExpr, idx])
    let some v ← getNatValue? val
      | throwTacticEx `cas goal s!"Could not evaluate target permutation at index {i}"
    targetArr := targetArr.push (v + 1)  -- 1-indexed for GAP
  -- Extract generators
  let gensArr ← whnf gensExpr
  let some gensSize ← getNatValue? (← whnf (← mkAppM ``Array.size #[gensExpr]))
    | throwTacticEx `cas goal "Could not determine number of generators"
  let mut gensData : Array (Array Nat) := #[]
  for gi in [:gensSize] do
    let genExpr ← whnf (← mkAppM ``Array.getD #[gensExpr, mkNatLit gi, targetPermExpr])
    let mut genArr : Array Nat := #[]
    for i in [:n] do
      let val ← whnf (← mkAppM ``Vector.get #[genExpr, mkNatLit i])
      let some v ← getNatValue? val
        | throwTacticEx `cas goal s!"Could not evaluate generator {gi} at index {i}"
      genArr := genArr.push (v + 1)
    gensData := gensData.push genArr
  -- Call CAS
  let problem : PermGroupMembershipProblem := {
    size := n
    generators := gensData
    target := targetArr
  }
  let response ← ctx.call (toMrdi problem)
  let result ← match fromMrdi? (α := PermGroupMembershipResult) response with
    | .ok r => pure r
    | .error e => throwTacticEx `cas goal s!"Failed to decode result: {e}"
  unless result.inGroup do
    throwTacticEx `cas goal "CAS reports permutation is not in the generated group"
  -- Introduce the word as existential witness
  let wordExpr ← mkArrayLit (mkConst ``Int) (result.word.toList.map fun i =>
    if i ≥ 0 then
      mkApp2 (mkConst ``Int.ofNat) (mkNatLit i.natAbs) (mkConst ``rfl)
    else
      mkApp (mkConst ``Int.negSucc) (mkNatLit (i.natAbs - 1)))
  let newGoal ← goal.existsIntro wordExpr
  -- Close: applyWord generators word = target, decidable on Fin n
  setGoals [newGoal]
  evalTactic (← `(tactic| native_decide))
  pure (← getGoals)

initialize do
  CAS.registerCASStrategy {
    name := `permGroupMembership
    priority := 1000
    match? := fun goal => do
      let target ← goal.getType
      pure (target.isAppOf ``Macaulean.InPermGroup)
    execute := executePermGroupMembership
  }

end Macaulean
