import Lean
import Macaulean.CAS.Strategy
import Macaulean.CAS.Tactic
import MRDI.CAS

open Lean Elab Tactic Meta
open MRDI.CAS

namespace Macaulean

/-! # Permutation Group Membership

Prove that a permutation is in the group generated by given generators.
The CAS (GAP via Oscar) finds a decomposition as a product of concrete
permutations. The kernel verifies by composing them — decidable on Fin n.

Design follows the same pattern as polynomial algebra:
- CAS provides ALL the data (the concrete permutations to compose)
- Kernel only checks a simple identity (composition = target)
- No inverse computation in the kernel path
-/

-- ============================================================================
-- Permutation definitions (no mathlib)
-- ============================================================================

/-- A permutation on n elements. `perm[i]` is the image of `i`. -/
abbrev Perm (n : Nat) := Vector (Fin n) n

/-- The identity permutation. -/
def Perm.id (n : Nat) : Perm n :=
  Vector.ofFn fun i => i

/-- Compose two permutations: (σ ∘ τ)(i) = σ(τ(i)). -/
def Perm.comp {n : Nat} (σ τ : Perm n) : Perm n :=
  Vector.ofFn fun i => σ[τ[i]]

/-- Compose a list of permutations left-to-right: apply first, then second, etc. -/
def Perm.composeList {n : Nat} (perms : List (Perm n)) : Perm n :=
  perms.foldl (init := Perm.id n) fun acc σ => Perm.comp σ acc

/-- `InPermGroup target generators` means `target` equals a composition of
some sequence of permutations. The CAS provides the sequence — which may
include generators and their inverses as concrete permutations. -/
def InPermGroup {n : Nat} (target : Perm n) (_generators : Array (Perm n)) : Prop :=
  ∃ steps : List (Perm n), Perm.composeList steps = target

-- ============================================================================
-- Expression extraction helpers
-- ============================================================================

private def extractFinVal (e : Lean.Expr) : MetaM Nat := do
  let e ← reduce e.consumeMData
  match_expr e with
  | Fin.mk _ v _ => do
      let some n ← getNatValue? v | return 0
      return n
  | _ => return 0

private partial def extractFinList (e : Lean.Expr) : MetaM (Array Nat) := do
  match_expr e.consumeMData with
  | List.cons _ hd tl =>
      let v ← extractFinVal hd
      let rest ← extractFinList tl
      return #[v] ++ rest
  | List.nil _ => return #[]
  | _ => return #[]

private def extractPermImages (e : Lean.Expr) : MetaM (Array Nat) := do
  let e ← reduce e
  let (fn, args) := e.consumeMData.getAppFnArgs
  if fn == ``Vector.mk && args.size == 4 then
    match_expr args[2]! with
    | Array.mk _ lst => extractFinList lst
    | _ => return #[]
  else return #[]

private partial def extractArrayPerms (e : Lean.Expr) : MetaM (Array (Array Nat)) := do
  let e ← reduce e
  match_expr e.consumeMData with
  | Array.mk _ lst =>
      let mut result : Array (Array Nat) := #[]
      let mut curr := lst
      while true do
        match_expr curr.consumeMData with
        | List.cons _ hd tl =>
            let images ← extractPermImages hd
            if images.isEmpty then return #[]
            result := result.push images
            curr := tl
        | List.nil _ => break
        | _ => return #[]
      return result
  | _ => return #[]

-- ============================================================================
-- Strategy
-- ============================================================================

private def executePermGroupMembership (ctx : CAS.CASContext) (goal : MVarId) :
    TacticM (List MVarId) := do
  let target ← goal.getType
  let (targetFn, targetArgs) := target.getAppFnArgs
  unless targetFn == ``Macaulean.InPermGroup && targetArgs.size == 3 do
    throwTacticEx `cas goal "Expected `InPermGroup target generators`"
  let nExpr := targetArgs[0]!
  let targetPermExpr := targetArgs[1]!
  let gensExpr := targetArgs[2]!
  let some n ← getNatValue? (← whnf nExpr)
    | throwTacticEx `cas goal "Expected a concrete n"
  let targetImages ← extractPermImages targetPermExpr
  if targetImages.isEmpty then
    throwTacticEx `cas goal "Could not extract target permutation"
  let gensImages ← extractArrayPerms gensExpr
  if gensImages.isEmpty then
    throwTacticEx `cas goal "Could not extract generators"
  -- Call CAS (1-indexed for GAP)
  let problem : PermGroupMembershipProblem := {
    size := n
    generators := gensImages.map (·.map (· + 1))
    target := targetImages.map (· + 1)
  }
  let response ← ctx.call (toMrdi problem)
  let result ← match fromMrdi? (α := PermGroupMembershipResult) response with
    | .ok r => pure r
    | .error e => throwTacticEx `cas goal s!"Failed to decode: {e}"
  unless result.inGroup do
    throwTacticEx `cas goal "Permutation is not in the generated group"
  -- CAS returns signed word: positive k = gen k, negative k = gen k inverse.
  -- Resolve each step to concrete permutation images (computed here, not in kernel).
  let computeInverse (fwd : Array Nat) : Array Nat := Id.run do
    let mut inv : Array Nat := .mkEmpty n
    for _ in [:n] do inv := inv.push 0
    for i in [:n] do
      if hi : i < fwd.size then
        inv := inv.set! fwd[i] i
    inv
  -- Build expanded generator table: [g1, g2, ..., g1⁻¹, g2⁻¹, ...]
  let nGens := gensImages.size
  let mut allGens : Array (Array Nat) := gensImages
  for gi in gensImages do
    allGens := allGens.push (computeInverse gi)
  -- Resolve word: each entry is a 1-indexed reference into allGens
  let mut resolvedSteps : Array (Array Nat) := #[]
  for letter in result.word do
    let idx := letter.natAbs - 1
    if h : idx < allGens.size then
      resolvedSteps := resolvedSteps.push allGens[idx]
  -- Build syntax for the list of concrete permutations
  let nLit := Syntax.mkNumLit (toString n)
  let mut stepSyntaxArr : Array (TSyntax `term) := #[]
  for images in resolvedSteps do
    let mut finLitArr : Array (TSyntax `term) := #[]
    for v in images do
      let vLit := Syntax.mkNumLit (toString v)
      let finSyn ← `(term| (⟨$vLit, by omega⟩ : Fin $nLit))
      finLitArr := finLitArr.push finSyn
    let vecSyn ← `(term| (⟨#[$[$finLitArr],*], by decide⟩ : Perm $nLit))
    stepSyntaxArr := stepSyntaxArr.push vecSyn
  let stepsListSyntax ← `(term| [$[$stepSyntaxArr],*])
  evalTactic (← `(tactic| exact ⟨$stepsListSyntax, by decide⟩))
  pure (← getGoals)

initialize do
  CAS.registerCASStrategy {
    name := `permGroupMembership
    priority := 1000
    match? := fun goal => do
      let target ← goal.getType
      pure (target.isAppOf ``Macaulean.InPermGroup)
    execute := executePermGroupMembership
  }

end Macaulean
