name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/macaulay2/testbot

    steps:
      - uses: actions/checkout@v7
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl
      - name: Check the Macaulay2 package
        run: cd m2 && M2 --stop -e 'check "Macaulean"' -e 'exit 0'
      - uses: leanprover/lean-action@v1
